/* +---------------------------------------------------------------------------+
   |              OpenBeam - C++ Finite Element Analysis library               |
   |                                                                           |
   |   Copyright (C) 2010-2026  Jose Luis Blanco Claraco                       |
   |                                                                           |
   | OpenBeam is free software: you can redistribute it and/or modify          |
   |     it under the terms of the GNU General Public License as published by  |
   |     the Free Software Foundation, either version 3 of the License, or     |
   |     (at your option) any later version.                                   |
   +---------------------------------------------------------------------------+
 */

// Every bundled example structure must parse and solve, give consistent
// results with both solvers and with meshing, and match its golden results.
//
// To regenerate the golden files after an intended change in results, run the
// tests with OPENBEAM_UPDATE_GOLDEN=1 and review the diff.

#include <mrpt/containers/yaml.h>

#include <cstdlib>
#include <filesystem>
#include <fstream>

#include "test_helpers.h"

using namespace openbeam;
using namespace openbeam::test;
namespace fs = std::filesystem;

namespace
{
const fs::path EXAMPLES_DIR = OPENBEAM_EXAMPLES_DIR;
const fs::path GOLDEN_DIR = OPENBEAM_GOLDEN_DIR;

std::vector<std::string> exampleNames()
{
  std::vector<std::string> names;
  for (const auto& f : fs::directory_iterator(EXAMPLES_DIR))
  {
    if (f.path().extension() == ".yaml")
    {
      names.push_back(f.path().stem().string());
    }
  }
  std::sort(names.begin(), names.end());
  return names;
}

std::string readFile(const fs::path& p)
{
  std::ifstream f(p);
  EXPECT_TRUE(f.is_open()) << p;
  return {std::istreambuf_iterator<char>(f), std::istreambuf_iterator<char>()};
}

bool allFinite(const Eigen::VectorXd& v) { return v.array().isFinite().all(); }

/// Results compared against the golden files: displacements, reactions and
/// internal forces at each element end.
std::map<std::string, std::vector<double>> resultsOf(const Solution& s)
{
  std::map<std::string, std::vector<double>> r;
  r["U_f"].assign(s.info.U_f.begin(), s.info.U_f.end());
  r["F_b"].assign(s.info.F_b.begin(), s.info.F_b.end());
  auto& st = r["element_stress"];
  for (const auto& es : s.stress.element_stress)
  {
    for (const auto& face : es)
    {
      for (int k = 0; k < 6; k++)
      {
        st.push_back(face[k]);
      }
    }
  }
  return r;
}

void writeGolden(const fs::path& p, const std::map<std::string, std::vector<double>>& r)
{
  std::ofstream f(p);
  f << "# Golden results, generated by examples_unittest. Do not edit.\n";
  for (const auto& [key, values] : r)
  {
    f << key << ": [";
    for (size_t i = 0; i < values.size(); i++)
    {
      f << (i ? ", " : "") << mrpt::format("%.17g", values[i]);
    }
    f << "]\n";
  }
}

class Examples : public testing::TestWithParam<std::string>
{
};

}  // namespace

TEST_P(Examples, SolvesAndMatchesGolden)
{
  const auto name = GetParam();
  const auto def = readFile(EXAMPLES_DIR / (name + ".yaml"));

  const auto s = solveYaml(def);
  ASSERT_TRUE(s.errors.empty());
  ASSERT_GT(s.info.U_f.size(), 0);
  EXPECT_TRUE(allFinite(s.info.U_f));
  EXPECT_TRUE(allFinite(s.info.F_b));

  const auto results = resultsOf(s);
  const auto goldenFile = GOLDEN_DIR / (name + ".yaml");
  if (std::getenv("OPENBEAM_UPDATE_GOLDEN"))
  {
    writeGolden(goldenFile, results);
    GTEST_SKIP() << "Golden file updated: " << goldenFile;
  }

  ASSERT_TRUE(fs::exists(goldenFile))
      << "Missing golden file, run with OPENBEAM_UPDATE_GOLDEN=1: " << goldenFile;
  const auto golden = mrpt::containers::yaml::FromFile(goldenFile.string());
  for (const auto& [key, values] : results)
  {
    const auto expected = golden[key].toStdVector<double>();
    ASSERT_EQ(values.size(), expected.size()) << key;

    // Absolute tolerance relative to the largest value of each kind, so
    // that round-off noise around zero does not count.
    double scale = 1e-12;
    for (double v : expected)
    {
      scale = std::max(scale, std::abs(v));
    }
    for (size_t i = 0; i < values.size(); i++)
    {
      EXPECT_NEAR(values[i], expected[i], 1e-9 * scale) << key << "[" << i << "]";
    }
  }
}

TEST_P(Examples, DenseAndSparseSolversAgree)
{
  const auto def = readFile(EXAMPLES_DIR / (GetParam() + ".yaml"));
  const auto dense = solveYaml(def, StaticSolverAlgorithm::Dense_LLT);
  const auto sparse = solveYaml(def, StaticSolverAlgorithm::Sparse_LLT);
  ASSERT_EQ(dense.info.U_f.size(), sparse.info.U_f.size());
  const double scale = std::max(dense.info.U_f.cwiseAbs().maxCoeff(), 1e-12);
  for (int i = 0; i < dense.info.U_f.size(); i++)
  {
    EXPECT_NEAR(sparse.info.U_f[i], dense.info.U_f[i], 1e-9 * scale);
  }
}

TEST_P(Examples, MeshingKeepsNodalDisplacements)
{
  // Exact beam elements: splitting them must not change the displacements
  // of the original nodes.
  const auto def = readFile(EXAMPLES_DIR / (GetParam() + ".yaml"));
  const auto s = solveYaml(def);
  ASSERT_TRUE(s.errors.empty());

  MeshParams mp;
  mp.max_element_length = 0.25;
  MeshOutputInfo mi;
  CStructureProblem meshed;
  StaticSolveProblemInfo meshedInfo;
  s.problem->mesh(meshed, mi, mp);
  meshed.solveStatic(meshedInfo);
  // (Truss bars are not split, so pure trusses keep all their elements)
  EXPECT_GE(meshed.getNumberOfElements(), s.problem->getNumberOfElements());

  const double scale = std::max(s.info.U_f.cwiseAbs().maxCoeff(), 1e-12);
  for (size_t node = 0; node < s.problem->getNumberOfNodes(); node++)
  {
    for (int k = 0; k < 6; k++)
    {
      const auto dof = static_cast<DoF_index>(k);
      const auto idx0 = s.problem->getDOFIndex(node, dof);
      if (idx0 == std::string::npos)
      {
        continue;
      }
      const auto idx1 = meshed.getDOFIndex(node, dof);
      ASSERT_NE(idx1, std::string::npos);
      const auto& t0 = s.info.build_info.dof_types.at(idx0);
      const auto& t1 = meshedInfo.build_info.dof_types.at(idx1);
      if (t0.free_index == std::string::npos)
      {
        continue;
      }
      ASSERT_NE(t1.free_index, std::string::npos);
      EXPECT_NEAR(meshedInfo.U_f[t1.free_index], s.info.U_f[t0.free_index], 1e-6 * scale)
          << "node " << node << " dof " << k;
    }
  }
}

INSTANTIATE_TEST_SUITE_P(
    All,
    Examples,
    testing::ValuesIn(exampleNames()),
    [](const testing::TestParamInfo<std::string>& info)
    {
      std::string n = info.param;
      std::replace_if(
          n.begin(), n.end(), [](char c) { return !std::isalnum(c); }, '_');
      return n;
    });
